[server]
headless = true
port = 8080
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
runOnSave = false

[theme]
base = "dark"
primaryColor = "#0054fdff"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"

[browser]
gatherUsageStats = false

[runner]
magicEnabled = false
fastReruns = true

[client]
showErrorDetails = false
toolbarMode = "minimal"